import {test} from 'node:test';import assert from 'node:assert/strict';
import {initPhysics,RoulettePhysics} from '../public/physics.js';
import {POCKETS,pocketAt,DT} from '../public/physics-shared.js';
import {freshRoom,act,tick,payout} from '../worker/game.js';
await initPhysics();
function finish(launch){const s=new RoulettePhysics(launch);for(let i=0;i<9000&&!s.result&&!s.failed;i++)s.step();const proof=s.proof();assert.ok(proof.result,'must settle naturally in a pocket');assert.equal(proof.ballSpeed,0);assert.equal(proof.wheelSpeed,0);assert.equal(pocketAt(proof.position,proof.rotation),proof.result);s.free();return proof;}
test('38 physical sectors and payouts include distinct 0 and 00',()=>{assert.equal(new Set(POCKETS).size,38);for(let i=0;i<38;i++){const a=i*Math.PI*2/38;assert.equal(pocketAt({x:.66*Math.sin(a),y:.038,z:-.66*Math.cos(a)},{x:0,y:0,z:0,w:1}),POCKETS[i]);assert.equal(payout('n:'+POCKETS[i],POCKETS[i]),36);}for(const n of ['0','00'])for(const k of ['red','black','even','odd','low','high'])assert.equal(payout(k,n),0);});
test('native CCD simulation: laps, deflectors, actual rest; identical replay',()=>{const launch={ballSpeed:7.2,wheelSpeed:1.18,radialSpeed:0};const a=finish(launch),b=finish(launch);assert.deepEqual(a,b);assert.ok(a.laps>2);assert.ok(a.contacts>0);assert.ok(a.step>600);});
test('different initial velocities settle without any target number',()=>{const outcomes=[];for(let i=0;i<6;i++){const p=finish({ballSpeed:6.8+i*.17,wheelSpeed:1.02+i*.06,radialSpeed:0});assert.ok(p.laps>2);outcomes.push(p.result);}assert.ok(new Set(outcomes).size>1);});
test('turns, public bets, ledger, native result and single payout',()=>{const s=freshRoom('ABCDEF'),now=Date.now();act(s,'a',{action:'join',name:'А'},now);act(s,'b',{action:'join',name:'Б'},now);act(s,'a',{action:'bet',key:'red',amount:100,id:'bet'},now);act(s,'a',{action:'bet',key:'red',amount:100,id:'bet'},now);assert.equal(s.players[0].balance,9900);assert.throws(()=>act(s,'b',{action:'bet',key:'black',amount:100},now));assert.throws(()=>act(s,'b',{action:'spin'},now));act(s,'a',{action:'spin'},now);assert.equal(s.result,null);assert.equal(s.spin.target,undefined);assert.equal(s.spin.result,undefined);const proof=finish(s.spin),at=s.spin.startedAt+proof.step*DT*1000+100;assert.throws(()=>act(s,'b',{action:'finish',spinId:s.spin.id,proof:{...proof,ballSpeed:1}},at));act(s,'b',{action:'finish',spinId:s.spin.id,proof},at);assert.equal(s.result,proof.result);const balance=s.players[0].balance;act(s,'a',{action:'finish',spinId:s.spin.id,proof},at+1);assert.equal(s.players[0].balance,balance);assert.equal(s.last[0].bets[0].amount,100);assert.equal(s.ledger.filter(e=>e.reason.startsWith('Ставка')).length,1);tick(s,at+6001);assert.equal(s.turn,s.players[1].id);act(s,'b',{action:'bet',key:'n:00',amount:50},at+6002);act(s,'b',{action:'undo'},at+6003);assert.equal(s.players[1].balance,10000);assert.equal(s.players[1].delta.amount,50);});
