import {mkdirSync,writeFileSync,readFileSync,readdirSync} from 'node:fs';
function copy(src,dest){mkdirSync(dest,{recursive:true});for(const e of readdirSync(src,{withFileTypes:true})){if(e.isDirectory())copy(src+'/'+e.name,dest+'/'+e.name);else writeFileSync(dest+'/'+e.name,readFileSync(src+'/'+e.name));}}
const shared=readFileSync('public/physics-shared.js','utf8').replaceAll('export ','');
const game=readFileSync('worker/game.js','utf8').replace("import { POCKETS, DT, ENGINE_VERSION, pocketAt } from '../public/physics-shared.js';",shared).replaceAll('export ','');
const source=readFileSync('worker/index.js','utf8').replace("import { freshRoom, act, publicState, tick } from './game.js';",game);
const assets={};function collect(dir,prefix=''){for(const e of readdirSync(dir,{withFileTypes:true})){if(e.isDirectory())collect(dir+'/'+e.name,prefix+'/'+e.name);else{const ext=e.name.split('.').pop(),key=prefix+'/'+e.name;const binary=ext==='png';assets[key]={binary,body:readFileSync(dir+'/'+e.name,binary?'base64':'utf8'),type:binary?'image/png':ext==='html'?'text/html; charset=utf-8':ext==='css'?'text/css; charset=utf-8':ext==='js'||ext==='mjs'?'text/javascript; charset=utf-8':'text/plain; charset=utf-8'};}}}collect('public');assets['/']=assets['/index.html'];
mkdirSync('dist/server',{recursive:true});mkdirSync('dist/.openai',{recursive:true});
writeFileSync('dist/server/index.js','const STATIC='+JSON.stringify(assets)+';\n'+source.replace('return env.ASSETS.fetch(request);',"const asset=STATIC[url.pathname];return asset?new Response(asset.binary?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache'}}):new Response('Not found',{status:404});"));
copy('public','dist/client');writeFileSync('dist/.openai/hosting.json',readFileSync('.openai/hosting.json'));copy('drizzle','dist/.openai/drizzle');console.log('Built physics roulette with local Rapier assets.');
